var markers = [
{"title": '0',
"lat": '0',
"lng": '0',
"description": '0',
"icon": 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png',
},
{"title": '2',
"lat": '2',
"lng": '2',
"description": '2',
"icon": 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png',
},
{"title": '3',
"lat": '3',
"lng": '3',
"description": '3',
"icon": 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png',
},
];